[package]
name = "skulpin-renderer"
version = "0.14.1"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"
description = "A vulkan renderer for skia, a component of skulpin"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aclysma/skulpin"
homepage = "https://github.com/aclysma/skulpin"
keywords = ["skia", "vulkan", "ash", "2d", "graphics"]
categories = ["graphics", "gui", "multimedia", "rendering", "visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# svg and shaper are deprecated. svg is always available, and shaper is included with textlayout. However, leaving them
# since skia_safe prints informative error messages. Complete now just contains textlayout
default = ["complete"]
shaper = ["skia-safe/shaper"]
svg = ["skia-safe/svg"]
textlayout = ["skia-safe/textlayout"]
complete = ["skia-safe/textlayout"]

[dependencies]
# rafx does not yet follow semver
rafx = { version = "=0.0.14", features = ["rafx-vulkan", "framework"] }
bincode = "1.3.1"
lazy_static = "1"

skia-safe = { version = "0.57.0", features = ["vulkan"] }
skia-bindings = { version = "0.57.0" }

log="0.4"
