name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [stable, beta]
        os: [windows-2019, ubuntu-20.04, macos-10.15]
        exclude:
          - os: macos-10.15
            toolchain: beta
          - os: windows-2019
            toolchain: beta
    runs-on: ${{ matrix.os }}
    needs: clean
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: ${{ runner.os }}-cargo-check-test-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      # The normal build with no features (renderer only)
      - name: Build
        run: cargo check
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

      # Verify winit 0.21 build works
      - name: Build winit 0.21
        run: cargo check --no-default-features --features=winit-21,winit-app
        if: ${{ runner.os == 'Linux' }}
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

      # Verify winit 0.22 build works
      - name: Build winit 0.22
        run: cargo check --no-default-features --features=winit-22,winit-app
        if: ${{ runner.os == 'Linux' }}
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

      # Verify winit 0.23 build works
      - name: Build winit 0.23
        run: cargo check --no-default-features --features=winit-23,winit-app
        if: ${{ runner.os == 'Linux' }}
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

      # Run tests (within winit 0.24)
      - name: Run tests
        run: cargo test --workspace --features=winit-24,winit-app
        if: ${{ runner.os == 'Linux' }}
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

      # Run tests (within winit 0.25)
      - name: Run tests
        run: cargo test --workspace --features=winit-25,winit-app
        if: ${{ runner.os == 'Linux' }}
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Check the format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: >
          cargo clippy
          --all-targets
